### ISSUE TITLE
viewBaseline not working after clean install

### ISSUE THREAD

**Issue by jjvz** [spaulaus/paass-laughing-conqueror#139] opened 2018-03-23 07:42 UTC
viewBaseline not working after clean install
## Expected Behavior
viewBaseline <mod> <ch> should create gnuplot of the selected channel baselines

## Current Behavior
After clean install of PAASS-LC, the viewBaseline executable is failing with error message: 
Cannot open load file 'Creating'
"Creating", line 0: util.c: No such file or directory

## Context
I've installed a clean version of PAASS-LC from the master repo. All the flags in ccmake is ON except for HRIBF. The output of 
$ which viewBaseline 
/opt/paass-lc/bin/viewBaseline

## Acceptance Criteria
viewBaseline <mod> <ch> creates gnuplot of the selected channel baselines

### Your Environment
|Operating system | CesntOS7 |
|Kernel Version | 3.10.0-693.11.6.el7.x86_64 |
|CMake Version | cmake version 3.9.1 |
|GCC Version | gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16) |
|ROOT Version | 6.13/01 |
|GSL Version | 2.4 |

### Steps to Reproduce
1. Install paass-lc according to wiki (however there are no specific instructions about which other switches should be ON)
2. run viewBaseline, e.g. viewBaseline 0 -1 
3. 

### Screenshots
![image](https://user-images.githubusercontent.com/18749257/37817125-5023b82e-2e7e-11e8-960e-feb072a75eb2.png)

**Comment by spaulaus** [comment] 2018-03-23 10:45
this is a duplicate of #26

**Comment by spaulaus** [comment] 2018-04-20 11:18
This issue was moved to spaulaus/paass#139

**Closed by spaulaus** 2018-04-20 11:18 UTC
Labels: Done, Duplicate
