### ISSUE TITLE
"find_tau" command in poll2 crashes poll2.

### ISSUE THREAD

**Issue by jjvz** [spaulaus/paass-laughing-conqueror#138] opened 2018-03-23 07:32 UTC
Running the "find_tau" command in poll2 causes the poll2 to exit improperly.
## Expected Behavior
Running the command "find_tau <mod> <ch> in poll2 should [I believe] calculate the tau for the active channel.
## Current Behavior
Running the "find_tau 0 8" command in poll2 causes the poll2 to exit improperly, with error message: "terminate called after throwing an instance of 'std::regex_error'" and the user is returned to the terminal command prompt while the lockfile /tmp/PixieInterface is not removed.

## Acceptance Criteria
find_tau <mod> <ch> in poll2 give tau for active channel.

### Your Environment
|Operating system | CesntOS7 |
|Kernel Version   | 3.10.0-693.11.6.el7.x86_64 |
|CMake Version    | cmake version 3.9.1 |
|GCC Version      | gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16) |
|ROOT Version     | 6.13/01 |
|GSL Version      | 2.4 |

### Steps to Reproduce
1. start poll2 
2. in poll2, call:
 find_tau 0 8

### Screenshots
![image](https://user-images.githubusercontent.com/18749257/37816780-009fe7ce-2e7d-11e8-8a66-b6a104b30ad4.png)

**Comment by spaulaus** [comment] 2018-03-23 11:04
If memory serves, this is a symptom of a different issue. `find_tau` has always been broken in the API. I don't think I've ever seen it work. I have noticed this error occur with `timedrun`.

**Comment by spaulaus** [comment] 2018-03-24 12:47
Closing since the issue isn't with `find_tau`

**Comment by spaulaus** [comment] 2018-04-20 11:18
This issue was moved to spaulaus/paass#138

**Closed by spaulaus** 2018-04-20 11:18 UTC
Labels: Done
